/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as CanvasEditorIndexRouteImport } from './routes/canvas-editor/index'
import { Route as EditorDemoRouteImport } from './routes/editor/demo'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasEditorIndexRoute = CanvasEditorIndexRouteImport.update({
  id: '/canvas-editor/',
  path: '/canvas-editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDemoRoute = EditorDemoRouteImport.update({
  id: '/editor/demo',
  path: '/editor/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/editor/demo': typeof EditorDemoRoute
  '/canvas-editor/': typeof CanvasEditorIndexRoute
  '/editor/': typeof EditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/editor/demo': typeof EditorDemoRoute
  '/canvas-editor': typeof CanvasEditorIndexRoute
  '/editor': typeof EditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/editor/demo': typeof EditorDemoRoute
  '/canvas-editor/': typeof CanvasEditorIndexRoute
  '/editor/': typeof EditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test' | '/editor/demo' | '/canvas-editor/' | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test' | '/editor/demo' | '/canvas-editor' | '/editor'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/editor/demo'
    | '/canvas-editor/'
    | '/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  EditorDemoRoute: typeof EditorDemoRoute
  CanvasEditorIndexRoute: typeof CanvasEditorIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-editor/': {
      id: '/canvas-editor/'
      path: '/canvas-editor'
      fullPath: '/canvas-editor/'
      preLoaderRoute: typeof CanvasEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/demo': {
      id: '/editor/demo'
      path: '/editor/demo'
      fullPath: '/editor/demo'
      preLoaderRoute: typeof EditorDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  EditorDemoRoute: EditorDemoRoute,
  CanvasEditorIndexRoute: CanvasEditorIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
