name: Setup Environment

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: Node Version
        required: false
        default: '22.19.0'
      pnpm-version:
        type: string
        description: PNPM Version
        required: false
        default: '10'
      registry-url:
        type: string
        description: NPM Registry URL
        required: false
        default: 'https://registry.npmjs.org'
      scope:
        type: string
        description: NPM Scope
        required: false
        default: '@ue-too'
      install-deps:
        type: boolean
        description: Whether to install dependencies
        required: false
        default: true
      build:
        type: boolean
        description: Whether to build packages
        required: false
        default: false
    secrets:
      NPM_TOKEN:
        required: false
      PAT:
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.scope }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Install dependencies
        if: ${{ inputs.install-deps }}
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile || pnpm install
          else
            pnpm install
          fi

      - name: Build packages
        if: ${{ inputs.build }}
        run: pnpm build
